# This is a basic workflow to help you get started with Actions

name: Ansible Deploy Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [labeled]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/verify-pr-label-action@v1.0.0
      with:
        github-token: '${{ secrets.PAT }}'
        valid-labels: 'deploy'
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: xr09/ansible-vps-starter
        token: ${{ secrets.PAT }}

    - name: Setup hostfile
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: hosts.ini.j2
        output_file: hosts.ini
      env:
        HOST_IP: '${{ secrets.HOSTNAME }}'

    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        playbook: install-php.yml
        inventory: hosts.ini
        galaxy_file: requirements.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'
        ANSIBLE_REMOTE_USER: '${{ secrets.USERNAME }}'
